/**
 * Commodore 64 KERNAL Jump Table and System Vectors
 * Official MOS KERNAL Standard API ($FF81 - $FFF3) & Hardware Vectors ($FFFA - $FFFF)
 */

export interface KernalJumpVector {
  address: number;
  hex: string;
  symbol: string;
  name: string;
  description: string;
  registers: string;
  category: "SCREEN" | "IO" | "FILE" | "MEMORY" | "INTERRUPT" | "CONTROL";
}

export const KERNAL_JUMP_VECTORS: KernalJumpVector[] = [
  {
    address: 0xFF81,
    hex: "$FF81",
    symbol: "SCINIT",
    name: "Initialize Screen Editor",
    description: "Initializes VIC-II registers, clears screen RAM, resets color RAM and cursor variables.",
    registers: "Registers used: A, X, Y",
    category: "SCREEN",
  },
  {
    address: 0xFF84,
    hex: "$FF84",
    symbol: "IOINIT",
    name: "Initialize I/O Devices",
    description: "Initializes CIA 1 ($DC00), CIA 2 ($DD00), sets default IRQ timer rates and IEC serial lines.",
    registers: "Registers used: A, X, Y",
    category: "IO",
  },
  {
    address: 0xFF87,
    hex: "$FF87",
    symbol: "RAMTAS",
    name: "Initialize RAM & Memory Limit",
    description: "Clears zero page ($0002-$00FF), tests RAM top ($A000/$FFFF), sets default cassette buffer ($033C).",
    registers: "Registers used: A, X, Y",
    category: "MEMORY",
  },
  {
    address: 0xFF8A,
    hex: "$FF8A",
    symbol: "RESTOR",
    name: "Restore Default I/O Vectors",
    description: "Restores default KERNAL indirect vectors in $0314-$0333 from ROM table at $FD1A.",
    registers: "Registers used: A, X, Y",
    category: "CONTROL",
  },
  {
    address: 0xFF8D,
    hex: "$FF8D",
    symbol: "VECTOR",
    name: "Read/Set Indirect Vectors",
    description: "Copies user indirect vectors to $0314-$0333 (Carry=0) or reads active vectors to RAM (Carry=1).",
    registers: "Input: X/Y=pointer to list, Carry; Uses: A, Y",
    category: "CONTROL",
  },
  {
    address: 0xFF90,
    hex: "$FF90",
    symbol: "SETMSG",
    name: "Control KERNAL Messages",
    description: "Controls display of system status messages (bit 7 = error messages, bit 6 = control messages).",
    registers: "Input: A = message control bits ($00, $40, $80, $C0)",
    category: "CONTROL",
  },
  {
    address: 0xFF93,
    hex: "$FF93",
    symbol: "SECOND",
    name: "Send Secondary Address on Serial Bus",
    description: "Sends secondary address after LISTEN on IEC serial bus.",
    registers: "Input: A = secondary address ($60-$6F)",
    category: "FILE",
  },
  {
    address: 0xFF96,
    hex: "$FF96",
    symbol: "TKSA",
    name: "Send Secondary Address after TALK",
    description: "Sends secondary address after TALK on IEC serial bus.",
    registers: "Input: A = secondary address ($60-$6F)",
    category: "FILE",
  },
  {
    address: 0xFF99,
    hex: "$FF99",
    symbol: "MEMTOP",
    name: "Read / Set Top of Memory",
    description: "Reads (Carry=1) or sets (Carry=0) highest usable RAM address (X/Y register pair).",
    registers: "Input/Output: X/Y=Address pointer, Carry flag",
    category: "MEMORY",
  },
  {
    address: 0xFF9C,
    hex: "$FF9C",
    symbol: "MEMBOT",
    name: "Read / Set Bottom of Memory",
    description: "Reads (Carry=1) or sets (Carry=0) lowest usable RAM address (X/Y register pair).",
    registers: "Input/Output: X/Y=Address pointer, Carry flag",
    category: "MEMORY",
  },
  {
    address: 0xFF9F,
    hex: "$FF9F",
    symbol: "SCNKEY",
    name: "Scan Keyboard Matrix",
    description: "Scans CIA1 matrix ($DC00/$DC01) and places decoded PETSCII key into keyboard buffer ($0277).",
    registers: "Registers used: A, X, Y",
    category: "IO",
  },
  {
    address: 0xFFA2,
    hex: "$FFA2",
    symbol: "SETTMO",
    name: "Set IEEE/IEC Bus Timeout",
    description: "Sets timeout inhibit flag for serial bus transfers.",
    registers: "Input: A = bit 7 timeout flag",
    category: "FILE",
  },
  {
    address: 0xFFA5,
    hex: "$FFA5",
    symbol: "IECIN",
    name: "Read Byte from IEC Serial Bus",
    description: "Handshakes and inputs single byte from talker device on serial bus.",
    registers: "Output: A = byte read; Status in $90",
    category: "FILE",
  },
  {
    address: 0xFFA8,
    hex: "$FFA8",
    symbol: "IECOUT",
    name: "Write Byte to IEC Serial Bus",
    description: "Outputs byte in Accumulator to listener device on serial bus.",
    registers: "Input: A = byte to transmit; Status in $90",
    category: "FILE",
  },
  {
    address: 0xFFAB,
    hex: "$FFAB",
    symbol: "UNTLK",
    name: "Send UNTALK on IEC Serial Bus",
    description: "Commands all talkers on serial bus to release bus lines.",
    registers: "Registers used: A, X",
    category: "FILE",
  },
  {
    address: 0xFFAE,
    hex: "$FFAE",
    symbol: "UNLSN",
    name: "Send UNLISTEN on IEC Serial Bus",
    description: "Commands all listeners on serial bus to release bus lines.",
    registers: "Registers used: A, X",
    category: "FILE",
  },
  {
    address: 0xFFB1,
    hex: "$FFB1",
    symbol: "LISTEN",
    name: "Command Serial Device to LISTEN",
    description: "Sends LISTEN command with device number (8-15) over IEC bus.",
    registers: "Input: A = device number ($08-$0F)",
    category: "FILE",
  },
  {
    address: 0xFFB4,
    hex: "$FFB4",
    symbol: "TALK",
    name: "Command Serial Device to TALK",
    description: "Sends TALK command with device number (8-15) over IEC bus.",
    registers: "Input: A = device number ($08-$0F)",
    category: "FILE",
  },
  {
    address: 0xFFB7,
    hex: "$FFB7",
    symbol: "READST",
    name: "Read I/O Status Word",
    description: "Returns current device status byte ($00 = OK, bit 6 = EOF, bit 7 = device not present).",
    registers: "Output: A = status byte (mirrors $0090 ST)",
    category: "IO",
  },
  {
    address: 0xFFBA,
    hex: "$FFBA",
    symbol: "SETLFS",
    name: "Set Logical File Parameters",
    description: "Sets Logical File Number (A), Device Number (X, e.g. 8=disk, 1=tape), and Secondary Address (Y).",
    registers: "Input: A = Logical File #, X = Device #, Y = Secondary address",
    category: "FILE",
  },
  {
    address: 0xFFBD,
    hex: "$FFBD",
    symbol: "SETNAM",
    name: "Set Filename Parameters",
    description: "Sets length of filename (A) and pointer to filename string in RAM (X=low, Y=high).",
    registers: "Input: A = length, X/Y = 16-bit address pointer",
    category: "FILE",
  },
  {
    address: 0xFFC0,
    hex: "$FFC0",
    symbol: "OPEN",
    name: "Open Logical File",
    description: "Opens logical channel to specified peripheral device or file using SETLFS/SETNAM.",
    registers: "Carry = 1 on error, A = error code",
    category: "FILE",
  },
  {
    address: 0xFFC3,
    hex: "$FFC3",
    symbol: "CLOSE",
    name: "Close Logical File",
    description: "Closes logical file channel (A = logical file number).",
    registers: "Input: A = logical file number",
    category: "FILE",
  },
  {
    address: 0xFFC6,
    hex: "$FFC6",
    symbol: "CHKIN",
    name: "Set Input Channel",
    description: "Redirects standard character input to logical file number in X.",
    registers: "Input: X = logical file number; Carry=1 on error",
    category: "IO",
  },
  {
    address: 0xFFC9,
    hex: "$FFC9",
    symbol: "CHKOUT",
    name: "Set Output Channel",
    description: "Redirects standard character output to logical file number in X.",
    registers: "Input: X = logical file number; Carry=1 on error",
    category: "IO",
  },
  {
    address: 0xFFCC,
    hex: "$FFCC",
    symbol: "CLRCHN",
    name: "Clear I/O Channels",
    description: "Restores default input (keyboard) and default output (screen 1702).",
    registers: "Registers used: A, X",
    category: "IO",
  },
  {
    address: 0xFFCF,
    hex: "$FFCF",
    symbol: "CHRIN / BASIN",
    name: "Input Character",
    description: "Reads next character from current input channel (keyboard buffer or file stream).",
    registers: "Output: A = PETSCII character",
    category: "IO",
  },
  {
    address: 0xFFD2,
    hex: "$FFD2",
    symbol: "CHROUT / BSOUT",
    name: "Output Character",
    description: "Outputs single PETSCII character in Accumulator to current output device (Screen, Disk, Printer).",
    registers: "Input: A = PETSCII character",
    category: "SCREEN",
  },
  {
    address: 0xFFD5,
    hex: "$FFD5",
    symbol: "LOAD",
    name: "Load RAM from Device",
    description: "Loads file into RAM (A=0 for LOAD, A=1 for VERIFY). X/Y specify relocation address if secondary addr is 0.",
    registers: "Input: A = 0/1, X/Y = Load address; Output: X/Y = End address + 1",
    category: "FILE",
  },
  {
    address: 0xFFD8,
    hex: "$FFD8",
    symbol: "SAVE",
    name: "Save RAM to Device",
    description: "Saves memory block from Zero Page pointer in A to ending address in X/Y.",
    registers: "Input: A = Zero page start pointer, X/Y = End address + 1",
    category: "FILE",
  },
  {
    address: 0xFFDB,
    hex: "$FFDB",
    symbol: "SETTIM",
    name: "Set Time of Day Software Clock",
    description: "Sets 24-hour jiffy clock in $A0-$A2 (A=MSB, X=middle, Y=LSB).",
    registers: "Input: A, X, Y = jiffies (1/60s PAL or NTSC)",
    category: "IO",
  },
  {
    address: 0xFFDE,
    hex: "$FFDE",
    symbol: "RDTIM",
    name: "Read Time of Day Software Clock",
    description: "Reads 24-hour jiffy clock counter from $A0-$A2 into A, X, Y.",
    registers: "Output: A = MSB, X = middle, Y = LSB",
    category: "IO",
  },
  {
    address: 0xFFE1,
    hex: "$FFE1",
    symbol: "STOP",
    name: "Check RUN/STOP Key",
    description: "Scans keyboard column for RUN/STOP keypress. Returns Zero flag Z=1 if pressed.",
    registers: "Output: Z flag = 1 if STOP key down, A = last row scan",
    category: "IO",
  },
  {
    address: 0xFFE4,
    hex: "$FFE4",
    symbol: "GETIN",
    name: "Get Character from Keyboard Buffer",
    description: "Fetches one character from keyboard queue. Returns A=0 if buffer is empty.",
    registers: "Output: A = PETSCII key code or $00",
    category: "IO",
  },
  {
    address: 0xFFE7,
    hex: "$FFE7",
    symbol: "CLALL",
    name: "Close All Channels and Files",
    description: "Aborts all active transfers, clears channel table and closes all logical files.",
    registers: "Registers used: A, X",
    category: "FILE",
  },
  {
    address: 0xFFEA,
    hex: "$FFEA",
    symbol: "UDTIM",
    name: "Update Real-Time Jiffy Clock",
    description: "Increments 24-hour software timer and triggers keyboard auto-repeat scan.",
    registers: "Registers used: A, X",
    category: "IO",
  },
  {
    address: 0xFFED,
    hex: "$FFED",
    symbol: "SCREEN",
    name: "Fetch Screen Dimensions",
    description: "Returns maximum screen columns in X (40) and rows in Y (25).",
    registers: "Output: X = 40 ($28), Y = 25 ($19)",
    category: "SCREEN",
  },
  {
    address: 0xFFF0,
    hex: "$FFF0",
    symbol: "PLOT",
    name: "Read / Set Cursor Position",
    description: "Reads (Carry=1) or sets (Carry=0) cursor screen position: X=row (0-24), Y=column (0-39).",
    registers: "Input/Output: X = Row (0-24), Y = Column (0-39), Carry flag",
    category: "SCREEN",
  },
  {
    address: 0xFFF3,
    hex: "$FFF3",
    symbol: "IOBASE",
    name: "Fetch Base Memory Address of I/O",
    description: "Returns start of memory mapped I/O page ($DC00 for CIA1 in X/Y).",
    registers: "Output: X = $00, Y = $DC",
    category: "IO",
  },
];

export interface HardwareVector {
  address: number;
  hex: string;
  name: string;
  defaultTargetHex: string;
  defaultTargetAddress: number;
  description: string;
}

export const HARDWARE_VECTORS: HardwareVector[] = [
  {
    address: 0xFFFA,
    hex: "$FFFA",
    name: "NMI (Non-Maskable Interrupt Vector)",
    defaultTargetHex: "$FE43",
    defaultTargetAddress: 0xFE43,
    description: "Triggered by Restore key, CIA2 Timer A/B, or expansion port cartridge line.",
  },
  {
    address: 0xFFFC,
    hex: "$FFFC",
    name: "RESET (Cold Start Vector)",
    defaultTargetHex: "$FCE2",
    defaultTargetAddress: 0xFCE2,
    description: "CPU Power-On and System Hard Reset entry point. Checks for 'CBM80' cartridge autostart.",
  },
  {
    address: 0xFFFE,
    hex: "$FFFE",
    name: "IRQ / BRK (Interrupt / Break Vector)",
    defaultTargetHex: "$FF48",
    defaultTargetAddress: 0xFF48,
    description: "Standard raster/timer maskable interrupt dispatcher. Redirects via $0314/$0315 to $EA31.",
  },
];
