/**
 * Polish C64 Classics Collection (Katalog Polskich Gier na Commodore 64)
 * Linked to repository: https://github.com/v3n0m3n0/Commodore-64-Web-Emulator-BASIC-D64-Extractor/tree/main/src/roms/games/polish_classics
 */

export interface PolishGameRomEntry {
  id: string;
  name: string;
  title: string;
  cleanTitle: string;
  ext: "d64" | "t64" | "prg" | "p00" | "tap";
  size: number;
  format: "D64" | "T64" | "PRG" | "TAP";
  genre: string;
  year: number | string;
  publisher?: string;
  author?: string;
  description: string;
  romUrl: string;
  directDownloadUrl: string;
}

export const GITHUB_POLISH_CLASSICS_REPO_BASE =
  "https://raw.githubusercontent.com/v3n0m3n0/Commodore-64-Web-Emulator-BASIC-D64-Extractor/main/src/roms/games/polish_classics/";

export const POLISH_CLASSICS_ROMS: PolishGameRomEntry[] = [
  {
    id: "agent-uop",
    name: "Agent UOP.t64",
    title: "Agent UOP",
    cleanTitle: "Agent UOP",
    ext: "t64",
    size: 49951,
    format: "T64",
    genre: "Przygodowa / Komedia",
    year: 1993,
    publisher: "ASF Polska",
    author: "Piotr R.",
    description: "Kultowa polska gra przygodowa wydana przez ASF. Gracz jako agent UOP rozwiązuje intrygi szpiegowskie, przesłuchuje podejrzanych i zabezpiecza tajne akta.",
    romUrl: "src/roms/games/polish_classics/Agent UOP.t64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Agent UOP.t64")}`,
  },
  {
    id: "arktyczne-polowanie",
    name: "Arktyczne Polowanie.PRG",
    title: "Arktyczne Polowanie",
    cleanTitle: "Arktyczne Polowanie",
    ext: "prg",
    size: 31127,
    format: "PRG",
    genre: "Zręcznościowa",
    year: 1990,
    publisher: "Polskie Oprogramowanie C64",
    author: "Krzysztof P.",
    description: "Klasyczna gra zręcznościowa na C64. Gracz poluje na arktyczne zwierzęta wśród lodowców i dryfujących kier, wykazując się refleksem i celnym okiem.",
    romUrl: "src/roms/games/polish_classics/Arktyczne Polowanie.PRG",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Arktyczne Polowanie.PRG")}`,
  },
  {
    id: "atak-sapera",
    name: "Atak Sapera.d64",
    title: "Atak Sapera",
    cleanTitle: "Atak Sapera",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Logiczna / Strategia",
    year: 1992,
    publisher: "Mirage Interactive",
    author: "Piotr K.",
    description: "Dynamiczna polska gra logiczno-taktyczna na dyskietkę 1541. Oczyszczaj strefy militarne z ładunków wybuchowych przy użyciu zaawansowanego sprzętu saperskiego.",
    romUrl: "src/roms/games/polish_classics/Atak Sapera.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Atak Sapera.d64")}`,
  },
  {
    id: "black-knight",
    name: "Black Knight.d64",
    title: "Black Knight",
    cleanTitle: "Black Knight",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Akcja / Rycerska",
    year: 1992,
    publisher: "Mirage Interactive",
    author: "Wojciech M.",
    description: "Klimatyczna polska gra akcji z grafiką wielokolorową VIC-II. Prowadź Czarnego Rycerza przez niebezpieczne zamczyska, pojedynkując się ze strażnikami.",
    romUrl: "src/roms/games/polish_classics/Black Knight.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Black Knight.d64")}`,
  },
  {
    id: "burmistrz",
    name: "Burmistrz.d64",
    title: "Burmistrz (Wydanie 1541 D64)",
    cleanTitle: "Burmistrz",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Strategia Ekonomiczna",
    year: 1992,
    publisher: "TimSoft",
    author: "Tomasz S.",
    description: "Kultowa polska gra ekonomiczno-strategiczna. Zarządzaj finansami miasta, inwestuj w szkoły, drogi i służbę zdrowia, dbając o zadowolenie obywateli przed kolejnymi wyborami.",
    romUrl: "src/roms/games/polish_classics/Burmistrz.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Burmistrz.d64")}`,
  },
  {
    id: "burmistrz-3",
    name: "Burmistrz 3.t64",
    title: "Burmistrz 3",
    cleanTitle: "Burmistrz 3",
    ext: "t64",
    size: 49951,
    format: "T64",
    genre: "Strategia Ekonomiczna",
    year: 1993,
    publisher: "TimSoft",
    author: "Tomasz S.",
    description: "Trzecia odsłona popularnej polskiej strategii kasetowej. Sprawdź swoje umiejętności gospodarcze w zarządzaniu rozrastającą się polską aglomeracją.",
    romUrl: "src/roms/games/polish_classics/Burmistrz 3.t64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Burmistrz 3.t64")}`,
  },
  {
    id: "chwat",
    name: "Chwat.d64",
    title: "Chwat",
    cleanTitle: "Chwat",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Zręcznościowa / Platformowa",
    year: 1991,
    publisher: "TimSoft",
    author: "Inflexion Development",
    description: "Polska zręcznościówka wydana przez TimSoft. Prowadź bohatera przez kolejne plansze najeżone pułapkami i wrogami, wymagające zwinności i precyzji.",
    romUrl: "src/roms/games/polish_classics/Chwat.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Chwat.d64")}`,
  },
  {
    id: "deadly-messengers",
    name: "Deadly Messengers.d64",
    title: "Deadly Messengers",
    cleanTitle: "Deadly Messengers",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Akcja / Shoot'em up",
    year: 1992,
    publisher: "TimSoft",
    author: "Agony Design",
    description: "Kosmiczny shoot'em up stworzony przez polską grupę Agony Design. Przebijaj się przez hordy wrogich myśliwców i bossów w obronie bazy gwiezdnej.",
    romUrl: "src/roms/games/polish_classics/Deadly Messengers.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Deadly Messengers.d64")}`,
  },
  {
    id: "detektyw",
    name: "Detektyw.d64",
    title: "Detektyw",
    cleanTitle: "Detektyw",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Kryminalna / Śledztwo",
    year: 1991,
    publisher: "Mirage Interactive",
    author: "Marek G.",
    description: "Klasyczne śledztwo kryminalne na C64. Gracz wciela się w postać prywatnego detektywa, analizuje zeznania świadków, poszlaki i motywy zbrodni.",
    romUrl: "src/roms/games/polish_classics/Detektyw.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Detektyw.d64")}`,
  },
  {
    id: "diamenty",
    name: "Diamenty.d64",
    title: "Diamenty",
    cleanTitle: "Diamenty",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Logiczna / Boulder Dash",
    year: 1990,
    publisher: "Polskie Oprogramowanie C64",
    author: "Stanisław D.",
    description: "Kultowa łamigłówka podziemna. Przekopuj tunele, uważaj na spadające głazy i zbierz wymaganą liczbę błyszczących diamentów przed upływem czasu.",
    romUrl: "src/roms/games/polish_classics/Diamenty.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Diamenty.d64")}`,
  },
  {
    id: "droga-morska-do-indii",
    name: "Droga morska do Indii.d64",
    title: "Droga morska do Indii",
    cleanTitle: "Droga morska do Indii",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Strategia / Handlowa",
    year: 1991,
    publisher: "Mirage",
    author: "Krzysztof K.",
    description: "Wypłyń z europejskich portów, zaopatrz flotyllę w zapasy i towary handlowe, pokonaj sztormy i odkryj bezpieczny szlak do Indii.",
    romUrl: "src/roms/games/polish_classics/Droga morska do Indii.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Droga morska do Indii.d64")}`,
  },
  {
    id: "ekonomia-feudalna",
    name: "Ekonomia Feudalna.d64",
    title: "Ekonomia Feudalna",
    cleanTitle: "Ekonomia Feudalna",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Strategia Ekonomiczna",
    year: 1991,
    publisher: "L.K. Avalon",
    author: "Janusz W.",
    description: "Głęboka gra ekonomiczna osadzona w średniowieczu. Zarządzaj ziemią feudalną, wyznaczaj daniny, magazynuj plony i broń poddanych przed głodem i najeźdźcami.",
    romUrl: "src/roms/games/polish_classics/Ekonomia Feudalna.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Ekonomia Feudalna.d64")}`,
  },
  {
    id: "familiada",
    name: "Familiada.d64",
    title: "Familiada",
    cleanTitle: "Familiada",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Teleturniej / Quiz",
    year: 1994,
    publisher: "Polskie Gry Komputerowe",
    author: "Karol S. & Team",
    description: "Niezapomniana adaptacja kultowego teleturnieju telewizyjnego. Dwie drużyny rywalizują w odgadywaniu najczęstszych odpowiedzi ankietowanych, z tablicą wyników i rundą finałową.",
    romUrl: "src/roms/games/polish_classics/Familiada.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Familiada.d64")}`,
  },
  {
    id: "fortuna-kolem-sie-toczy",
    name: "Fortuna kolem sie toczy.d64",
    title: "Fortuna kołem się toczy",
    cleanTitle: "Fortuna kolem sie toczy",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Teleturniej / Słowna",
    year: 1993,
    publisher: "Mirage",
    author: "Grzegorz P.",
    description: "Teleturniej literowy z charakterystycznym kołem z nagrodami i polami 'Bankrut'. Odgaduj polskie hasła z różnych kategorii i gromadź wirtualne miliony złotych.",
    romUrl: "src/roms/games/polish_classics/Fortuna kolem sie toczy.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Fortuna kolem sie toczy.d64")}`,
  },
  {
    id: "hammurabi",
    name: "Hammurabi.d64",
    title: "Hammurabi",
    cleanTitle: "Hammurabi",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Strategia / Symulacja",
    year: 1988,
    publisher: "C64 Poland",
    author: "Polska Demoscena",
    description: "Klasyczna gra strategiczno-zarządcza. Jako król Hammurabi decyduj ile akrów obsiać, ile ziarna rozdać ludności na wyżywienie i jak ustrzec zapasy przed plagami szczurów.",
    romUrl: "src/roms/games/polish_classics/Hammurabi.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Hammurabi.d64")}`,
  },
  {
    id: "hans-kloss",
    name: "Hans Kloss.d64",
    title: "Hans Kloss",
    cleanTitle: "Hans Kloss",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Szpiegowska / Platformowa / Logiczna",
    year: 1992,
    publisher: "L.K. Avalon",
    author: "Janusz Pelc, Maciej Miąsik",
    description: "Prawdziwa legenda polskiego oprogramowania retro stworzona przez Janusza Pelca i Macieja Miąsika. Przemierzaj podziemia kwatery głównej, unikaj strażników, rozwiązuj zagadki i sfotografuj plany broni V.",
    romUrl: "src/roms/games/polish_classics/Hans Kloss.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Hans Kloss.d64")}`,
  },
  {
    id: "hobbit-czyli-w-te-i-wewte",
    name: "Hobbit czyli w te i wewte.d64",
    title: "Hobbit czyli w te i wewte",
    cleanTitle: "Hobbit czyli w te i wewte",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Przygodowa Tekstowa / RPG",
    year: 1990,
    publisher: "Mirage Interactive",
    author: "Paweł M.",
    description: "Niezwykła tekstowa wyprawa hobbita Bilbo Bagginsa i krasnoludów pod Samotną Górę. Eksploruj Śródziemie, wchodź w interakcje z postaciami i zmierz się ze smokiem Smaugiem.",
    romUrl: "src/roms/games/polish_classics/Hobbit czyli w te i wewte.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Hobbit czyli w te i wewte.d64")}`,
  },
  {
    id: "kaktus",
    name: "Kaktus.prg",
    title: "Kaktus",
    cleanTitle: "Kaktus",
    ext: "prg",
    size: 25412,
    format: "PRG",
    genre: "Zręcznościowa",
    year: 1991,
    publisher: "Polskie Oprogramowanie C64",
    author: "Tomasz K.",
    description: "Wciągająca gra zręcznościowa wymagająca szybkiego czasu reakcji. Pokonuj kolejne etapy pustynne, omijając pułapki i zbierając bonusowe krople wody.",
    romUrl: "src/roms/games/polish_classics/Kaktus.prg",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Kaktus.prg")}`,
  },
  {
    id: "klatwa",
    name: "Klatwa.d64",
    title: "Klątwa",
    cleanTitle: "Klatwa",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Przygoda / RPG / Izometryczna",
    year: 1990,
    publisher: "L.K. Avalon",
    author: "Roland Pantoła",
    description: "Wybitne dzieło Rolanda Pantoły wydane przez L.K. Avalon. Odkrywaj tajemnice starożytnych zaklęć, zbieraj magiczne artefakty i zdejmij mroczną klątwę ciążącą nad krainą.",
    romUrl: "src/roms/games/polish_classics/Klatwa.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Klatwa.d64")}`,
  },
  {
    id: "klemens",
    name: "Klemens.d64",
    title: "Klemens",
    cleanTitle: "Klemens",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Platformowa / Zręcznościowa",
    year: 1992,
    publisher: "ASF",
    author: "Piotr B.",
    description: "Polska platformówka pełna sekretnych przejść i ruchomych kładek. Skacz, wspinaj się po drabinach i zbieraj klucze otwierające przejścia do kolejnych komnat.",
    romUrl: "src/roms/games/polish_classics/Klemens.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Klemens.d64")}`,
  },
  {
    id: "klepkomania",
    name: "Klepkomania.t64",
    title: "Klepkomania",
    cleanTitle: "Klepkomania",
    ext: "t64",
    size: 49951,
    format: "T64",
    genre: "Logiczna / Układanka",
    year: 1993,
    publisher: "TimSoft",
    author: "Artur S.",
    description: "Wymagająca gra logiczna na taśmę kasetową. Przesuwaj kafelki w odpowiedniej sekwencji, by ułożyć docelową mozaikę przed upływem limitu ruchów.",
    romUrl: "src/roms/games/polish_classics/Klepkomania.t64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Klepkomania.t64")}`,
  },
  {
    id: "kolo-fortuny",
    name: "Kolo Fortuny.d64",
    title: "Koło Fortuny (VERMES, 1993)",
    cleanTitle: "Kolo Fortuny",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Teleturniej / Słowna / Logiczna",
    year: 1993,
    publisher: "VERMES",
    author: "VERMES Software",
    description: "Kultowy polski teleturniej z Wojciechem Pijanowskim i Magdą Masny na C64. Kręć kołem, unikaj bankruta, odgaduj spółgłoski i rozwiązuj hasła z różnych kategorii!",
    romUrl: "src/roms/games/polish_classics/Kolo Fortuny.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Kolo Fortuny.d64")}`,
  },
  {
    id: "kolony-4-4",
    name: "Kolony 4.4.d64",
    title: "Kolony 4.4",
    cleanTitle: "Kolony 4.4",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Kosmiczna Strategia / Sci-Fi",
    year: 1993,
    publisher: "L.K. Avalon",
    author: "Robert M.",
    description: "Rozbudowana polska strategia kosmiczna. Zakładaj pozaziemskie bazy, wydobywaj rzadkie minerały, rozwijaj technologię i odpieraj zagrożenia z głębi kosmosu.",
    romUrl: "src/roms/games/polish_classics/Kolony 4.4.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Kolony 4.4.d64")}`,
  },
  {
    id: "kolormania",
    name: "Kolormania.t64",
    title: "Kolormania",
    cleanTitle: "Kolormania",
    ext: "t64",
    size: 49951,
    format: "T64",
    genre: "Logiczna / Kolory",
    year: 1992,
    publisher: "TimSoft",
    author: "Wiesław K.",
    description: "Gra logiczna wykorzystująca 16-kolorową paletę Commodore 64. Łącz odpowiadające sobie pola kolorystyczne i oczyszczaj planszę z barwnych kryształów.",
    romUrl: "src/roms/games/polish_classics/Kolormania.t64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Kolormania.t64")}`,
  },
  {
    id: "later-preview",
    name: "Later Preview.t64",
    title: "Later Preview",
    cleanTitle: "Later Preview",
    ext: "t64",
    size: 49951,
    format: "T64",
    genre: "Demoscena / Prezentacja",
    year: 1993,
    publisher: "C64 Demoscene Poland",
    author: "Polska Scena C64",
    description: "Demoscenowa wersja zapowiedzi polskiej produkcji na C64 prezentująca możliwości silnika graficznego, scroller rastrowy i zaawansowaną kompozycję dźwiękową.",
    romUrl: "src/roms/games/polish_classics/Later Preview.t64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Later Preview.t64")}`,
  },
  {
    id: "lingos",
    name: "Lingos.PRG",
    title: "Lingos",
    cleanTitle: "Lingos",
    ext: "prg",
    size: 18234,
    format: "PRG",
    genre: "Logiczna / Językowa",
    year: 1991,
    publisher: "Polskie Oprogramowanie C64",
    author: "Marek T.",
    description: "Intelektualna gra słowna na C64. Gracz analizuje trafienia liter i ich pozycje, aby w kilku krokach odgadnąć wylosowane polskie słowo.",
    romUrl: "src/roms/games/polish_classics/Lingos.PRG",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Lingos.PRG")}`,
  },
  {
    id: "machina-prawdy",
    name: "Machina Prawdy.t64",
    title: "Machina Prawdy",
    cleanTitle: "Machina Prawdy",
    ext: "t64",
    size: 49951,
    format: "T64",
    genre: "Psychologiczna / Quiz",
    year: 1992,
    publisher: "TimSoft",
    author: "Tomasz G.",
    description: "Nietypowa polska produkcja łącząca quiz psychologiczny z wariografem na Commodore 64. Odpowiadaj na pytania i sprawdź, czy komputer wykryje blef.",
    romUrl: "src/roms/games/polish_classics/Machina Prawdy.t64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Machina Prawdy.t64")}`,
  },
  {
    id: "madrax",
    name: "Madrax.d64",
    title: "Madrax",
    cleanTitle: "Madrax",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Sci-Fi / Akcja",
    year: 1992,
    publisher: "TimSoft",
    author: "Agony Design",
    description: "Polska gra akcji w klimacie cybernetycznym. Przemierzaj korytarze stacji orbitalnej Madrax, eliminując zbuntowane maszyny bojowe.",
    romUrl: "src/roms/games/polish_classics/Madrax.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Madrax.d64")}`,
  },
  {
    id: "mapa-europy",
    name: "Mapa Europy.d64",
    title: "Mapa Europy",
    cleanTitle: "Mapa Europy",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Edukacyjna / Geografia",
    year: 1991,
    publisher: "TimSoft",
    author: "Stanisław D.",
    description: "Znakomity polski program edukacyjno-quizowy. Wskazuj państwa, stolice, rzeki i łańcuchy górskie na wektorowej mapie Europy wyświetlanej na ekranie C64.",
    romUrl: "src/roms/games/polish_classics/Mapa Europy.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Mapa Europy.d64")}`,
  },
  {
    id: "moon-patrol",
    name: "Moon Patrol.d64",
    title: "Moon Patrol (Polska Wersja)",
    cleanTitle: "Moon Patrol",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Zręcznościowa / Kosmiczna",
    year: 1990,
    publisher: "Retro Poland",
    author: "Polska Scena C64",
    description: "Kultowy rajd po powierzchni księżyca. Steruj łazikiem bojowym, przeskakuj wyrwy w gruncie, niszcz miny i odpieraj ataki statków obcych.",
    romUrl: "src/roms/games/polish_classics/Moon Patrol.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Moon Patrol.d64")}`,
  },
  {
    id: "najemnik",
    name: "Najemnik.d64",
    title: "Najemnik",
    cleanTitle: "Najemnik",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Akcja / Labirynt",
    year: 1993,
    publisher: "L.K. Avalon",
    author: "Roland Pantoła",
    description: "Rozbudowana gra akcji od L.K. Avalon. Jako tytułowy najemnik wykonujesz niebezpieczne misje sabotażowe w silnie strzeżonych bazach nieprzyjaciela.",
    romUrl: "src/roms/games/polish_classics/Najemnik.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Najemnik.d64")}`,
  },
  {
    id: "najemnik-powrot",
    name: "Najemnik - Powrot.d64",
    title: "Najemnik - Powrót",
    cleanTitle: "Najemnik - Powrot",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Akcja / Labirynt",
    year: 1992,
    publisher: "L.K. Avalon",
    author: "Roland Pantoła",
    description: "Kontynuacja taktycznego hitu na C64. Powróć na pole bitwy z nowymi typami broni, pułapkami laserowymi i zaawansowanym systemem komputerów pokładowych.",
    romUrl: "src/roms/games/polish_classics/Najemnik - Powrot.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Najemnik - Powrot.d64")}`,
  },
  {
    id: "namiestnik",
    name: "Namiestnik.d64",
    title: "Namiestnik",
    cleanTitle: "Namiestnik",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Strategia Historyczna",
    year: 1992,
    publisher: "Mirage Interactive",
    author: "Krzysztof M.",
    description: "Historyczna gra strategiczna. Jako namiestnik królewski podejmuj decyzje gospodarcze, zwołuj sejmiki, pobieraj podatki i formuj chorągwie wojskowe.",
    romUrl: "src/roms/games/polish_classics/Namiestnik.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Namiestnik.d64")}`,
  },
  {
    id: "oel-pompowacze",
    name: "Oel Pompowacze.d64",
    title: "Oel Pompowacze",
    cleanTitle: "Oel Pompowacze",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Symulacja Naftowa / Biznes",
    year: 1991,
    publisher: "TimSoft",
    author: "Dariusz Z.",
    description: "Polska gra ekonomiczna w branży naftowej. Inwestuj w szyby wiertnicze, rurociągi i tankowce, spekulując cenami czarnego złota na rynkach światowych.",
    romUrl: "src/roms/games/polish_classics/Oel Pompowacze.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Oel Pompowacze.d64")}`,
  },
  {
    id: "operacja-proboszcz",
    name: "Operacja Proboszcz.t64",
    title: "Operacja Proboszcz",
    cleanTitle: "Operacja Proboszcz",
    ext: "t64",
    size: 49951,
    format: "T64",
    genre: "Komediowa Przygodowa",
    year: 1993,
    publisher: "ASF",
    author: "Grzegorz C.",
    description: "Niezwykle zabawna gra przygodowa wydana przez ASF. Rozwiązuj codzienne problemy parafii, zbieraj fundusze na remont kościoła i wchodź w komiczne dialogi z mieszkańcami.",
    romUrl: "src/roms/games/polish_classics/Operacja Proboszcz.t64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Operacja Proboszcz.t64")}`,
  },
  {
    id: "ortografia",
    name: "Ortografia.d64",
    title: "Ortografia",
    cleanTitle: "Ortografia",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Edukacyjna / Język Polski",
    year: 1991,
    publisher: "TimSoft",
    author: "Tomasz G.",
    description: "Klasyczny polski program dydaktyczny z TimSoftu. Wybierz reguły ortograficzne, uzupełniaj brakujące litery w zdaniach i zdobywaj oceny od wirtualnego nauczyciela.",
    romUrl: "src/roms/games/polish_classics/Ortografia.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Ortografia.d64")}`,
  },
  {
    id: "ortotris",
    name: "Ortotris.t64",
    title: "Ortotris",
    cleanTitle: "Ortotris",
    ext: "t64",
    size: 49951,
    format: "T64",
    genre: "Logiczna / Słowna",
    year: 1993,
    publisher: "TimSoft",
    author: "Tomasz G.",
    description: "Oryginalna gra łącząca spadające klocki z nauką języka. Łącz litery i sylaby w kompletne wyrazy, zanim studnia zapełni się elementami.",
    romUrl: "src/roms/games/polish_classics/Ortotris.t64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Ortotris.t64")}`,
  },
  {
    id: "playfull-professor",
    name: "Playfull Professor.d64",
    title: "Playfull Professor",
    cleanTitle: "Playfull Professor",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Quiz Naukowy / Logiczna",
    year: 1992,
    publisher: "TimSoft",
    author: "Agony Design",
    description: "Znakomity polski quiz naukowy w laboratorium szalonego profesora. Rozwiązuj łamigłówki naukowe, przeprowadzaj eksperymenty i zdobywaj stopnie naukowe.",
    romUrl: "src/roms/games/polish_classics/Playfull Professor.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Playfull Professor.d64")}`,
  },
  {
    id: "poker",
    name: "Poker.d64",
    title: "Poker",
    cleanTitle: "Poker",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Karciana / Kasyno",
    year: 1990,
    publisher: "Polskie Oprogramowanie C64",
    author: "Marek P.",
    description: "Symulacja pokera dobieranego na Commodore 64. Wymieniaj karty, licytuj pule i blefuj, aby ograć komputerowych przeciwników przy zielonym stoliku.",
    romUrl: "src/roms/games/polish_classics/Poker.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Poker.d64")}`,
  },
  {
    id: "poker-po-polsku",
    name: "Poker po polsku.d64",
    title: "Poker po polsku",
    cleanTitle: "Poker po polsku",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Karciana / Humorystyczna",
    year: 1991,
    publisher: "Mirage Interactive",
    author: "Krzysztof W.",
    description: "Humorystyczne wydanie pokera z animowanymi podobiznami rywali, polskimi odzywkami i unikalnym systemem licytacji monet PLZ.",
    romUrl: "src/roms/games/polish_classics/Poker po polsku.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Poker po polsku.d64")}`,
  },
  {
    id: "prawo-boylea",
    name: "Prawo Boylea.d64",
    title: "Prawo Boylea",
    cleanTitle: "Prawo Boylea",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Fizyczna / Edukacyjna",
    year: 1990,
    publisher: "TimSoft",
    author: "Prof. Janusz K.",
    description: "Fascynujący program naukowy symulujący ciśnienie, objętość i temperaturę gazu w cylindrze z tłokiem wedle równań Boyle'a-Mariotte'a.",
    romUrl: "src/roms/games/polish_classics/Prawo Boylea.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Prawo Boylea.d64")}`,
  },
  {
    id: "robbo",
    name: "Robbo.d64",
    title: "Robbo",
    cleanTitle: "Robbo",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Logiczna / Zręcznościowa",
    year: 1989,
    publisher: "L.K. Avalon",
    author: "Janusz Pelc",
    description: "Niekwestionowany klasyk polskiego gamedevu autorstwa Janusza Pelca. Poprowadź małego robota przez dziesiątki planet, zbierając części zamienne i unikając niebezpiecznych potworów.",
    romUrl: "src/roms/games/polish_classics/Robbo.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Robbo.d64")}`,
  },
  {
    id: "samowolka",
    name: "Samowolka.d64",
    title: "Samowolka",
    cleanTitle: "Samowolka",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Przygodowa / Komedia Wojenna",
    year: 1992,
    publisher: "ASF",
    author: "Piotr R.",
    description: "Kultowa gra przygodowa w realiach polskiego wojska lat 90. Wymknij się z koszar poza zasięg wzroku oficera dyżurnego i dotrzyj na wiejską zabawę.",
    romUrl: "src/roms/games/polish_classics/Samowolka.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Samowolka.d64")}`,
  },
  {
    id: "saper",
    name: "Saper.d64",
    title: "Saper",
    cleanTitle: "Saper",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Logiczna",
    year: 1993,
    publisher: "Polskie Oprogramowanie C64",
    author: "Tomasz L.",
    description: "Znakomita implementacja sapera na Commodore 64. Oznaczaj chorągiewkami ukryte miny, dedukuj bezpieczne pola i bij rekordy czasowe.",
    romUrl: "src/roms/games/polish_classics/Saper.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Saper.d64")}`,
  },
  {
    id: "saper-2",
    name: "Saper 2.d64",
    title: "Saper 2",
    cleanTitle: "Saper 2",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Logiczna",
    year: 1992,
    publisher: "Polskie Oprogramowanie C64",
    author: "Tomasz L.",
    description: "Rozszerzona wersja Sapera z różnymi poziomami trudności, edytorem plansz i dynamicznie zmieniającymi się warunkami saperskimi.",
    romUrl: "src/roms/games/polish_classics/Saper 2.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Saper 2.d64")}`,
  },
  {
    id: "slaterman",
    name: "Slaterman.t64",
    title: "Slaterman",
    cleanTitle: "Slaterman",
    ext: "t64",
    size: 49951,
    format: "T64",
    genre: "Platformowa / Akcja",
    year: 1992,
    publisher: "TimSoft",
    author: "Inflexion Development",
    description: "Szybka gra platformowa wydana przez TimSoft. Walcz z wrogami, zbieraj power-upy i przechodź wielopoziomowe etapy pełne pułapek.",
    romUrl: "src/roms/games/polish_classics/Slaterman.t64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Slaterman.t64")}`,
  },
  {
    id: "slownik-angielsko-polski",
    name: "Slownik Angielsko-Polski.d64",
    title: "Słownik Angielsko-Polski",
    cleanTitle: "Slownik Angielsko-Polski",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Edukacyjna / Słownik",
    year: 1991,
    publisher: "TimSoft",
    author: "Tomasz G.",
    description: "Pionierski polski słownik komputerowy na C64. Błyskawiczne wyszukiwanie haseł, tłumaczenia w obu kierunkach oraz moduł testowania słówek.",
    romUrl: "src/roms/games/polish_classics/Slownik Angielsko-Polski.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Slownik Angielsko-Polski.d64")}`,
  },
  {
    id: "spekulant-europejski",
    name: "Spekulant Europejski.d64",
    title: "Spekulant Europejski",
    cleanTitle: "Spekulant Europejski",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Giełdowa / Finansowa",
    year: 1992,
    publisher: "Mirage Interactive",
    author: "Michał K.",
    description: "Zaawansowana gra finansowa. Śledź kursy marek niemieckich, franków i dolarów, przewiduj inflację i zbuduj potęgę finansową na rynku europejskim.",
    romUrl: "src/roms/games/polish_classics/Spekulant Europejski.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Spekulant Europejski.d64")}`,
  },
  {
    id: "splitter",
    name: "Splitter.d64",
    title: "Splitter",
    cleanTitle: "Splitter",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Zręcznościowa / Akcja",
    year: 1991,
    publisher: "TimSoft",
    author: "Agony Design",
    description: "Ekscytująca gra zręcznościowa stworzona przez polską demogrupę Agony Design. Dziel spadające cząstki, unikając kolizji z barierami energetycznymi.",
    romUrl: "src/roms/games/polish_classics/Splitter.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Splitter.d64")}`,
  },
  {
    id: "squash",
    name: "Squash.d64",
    title: "Squash",
    cleanTitle: "Squash",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Sportowa",
    year: 1990,
    publisher: "Polskie Oprogramowanie C64",
    author: "Paweł W.",
    description: "Realistyczna gra sportowa na Commodore 64. Odbijaj piłkę rakietą od ścian kortu, nadając jej rotację i prędkość, by przechytrzyć rywala.",
    romUrl: "src/roms/games/polish_classics/Squash.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Squash.d64")}`,
  },
  {
    id: "szlak-miecza",
    name: "Szlak Miecza.d64",
    title: "Szlak Miecza",
    cleanTitle: "Szlak Miecza",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Fantasy RPG / Przygoda",
    year: 1992,
    publisher: "L.K. Avalon",
    author: "Artur M.",
    description: "Wspaniałe polskie RPG od L.K. Avalon. Stwórz drużynę wojowników i magów, zwiedzaj starożytne grobowce, zbieraj oręż i wypełnij pradawne proroctwo.",
    romUrl: "src/roms/games/polish_classics/Szlak Miecza.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Szlak Miecza.d64")}`,
  },
  {
    id: "trener",
    name: "Trener.d64",
    title: "Trener",
    cleanTitle: "Trener",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Manager Piłkarski",
    year: 1991,
    publisher: "Mirage Interactive",
    author: "Mariusz J.",
    description: "Kultowy manager piłkarski na C64. Wybierz polski klub, ustalaj skład meczowy, kupuj gwiazdy futbolu i poprowadź drużynę do mistrzostwa i europejskich pucharów.",
    romUrl: "src/roms/games/polish_classics/Trener.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Trener.d64")}`,
  },
  {
    id: "triada",
    name: "Triada.d64",
    title: "Triada",
    cleanTitle: "Triada",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Klasyczna Gra C64 / Strategia",
    year: 1991,
    publisher: "Mirage",
    author: "Krzysztof M.",
    description: "Taktyczna gra planszowa na ekranie C64. Opanowuj kluczowe prowincje, zawieraj sojusze i wykorzystaj przewagę militarną do pokonania wrogiej Triady.",
    romUrl: "src/roms/games/polish_classics/Triada.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Triada.d64")}`,
  },
  {
    id: "twierdza",
    name: "Twierdza.d64",
    title: "Twierdza",
    cleanTitle: "Twierdza",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Strategia Obronna",
    year: 1991,
    publisher: "L.K. Avalon",
    author: "Piotr S.",
    description: "Polska strategia obronna. Rozmieszczaj łuczników na murach, wzmacniaj bramy i odeprzyj szturm nieprzyjacielskich taranów i katapult.",
    romUrl: "src/roms/games/polish_classics/Twierdza.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Twierdza.d64")}`,
  },
  {
    id: "war-for-the-crown-2",
    name: "War for the Crown 2 - Successors of the Throne.d64",
    title: "War for the Crown 2",
    cleanTitle: "War for the Crown 2 - Successors of the Throne",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Strategia Rycerska / Wojenna",
    year: 1993,
    publisher: "Mirage Interactive",
    author: "Wojciech M.",
    description: "Druga część znakomitej polskiej strategii wojennej. Zarządzaj prowincjami królestwa, rekrutuj rycerstwo i tocz turowe bitwy o tron królewski.",
    romUrl: "src/roms/games/polish_classics/War for the Crown 2 - Successors of the Throne.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("War for the Crown 2 - Successors of the Throne.d64")}`,
  },
  {
    id: "wladca",
    name: "Wladca.d64",
    title: "Władca",
    cleanTitle: "Wladca",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Strategia Królewska",
    year: 1991,
    publisher: "L.K. Avalon",
    author: "Stanisław D.",
    description: "Wielka polska gra strategiczna. Jako władca dbasz o rozwój rzemiosła, handel międzynarodowy, relacje z sąsiadami i potęgę militarną państwa.",
    romUrl: "src/roms/games/polish_classics/Wladca.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Wladca.d64")}`,
  },
  {
    id: "wladcy-ciemnosci",
    name: "Wladcy ciemnosci.d64",
    title: "Władcy Ciemności",
    cleanTitle: "Wladcy ciemnosci",
    ext: "d64",
    size: 174848,
    format: "D64",
    genre: "Przygoda / Izometryczna RPG",
    year: 1992,
    publisher: "L.K. Avalon",
    author: "Roland Pantoła",
    description: "Legendarne dzieło Rolanda Pantoły. Wyrusz do podziemi cytadeli Władców Ciemności, rzucaj potężne czary i staw czoła demonom z innego wymiaru.",
    romUrl: "src/roms/games/polish_classics/Wladcy ciemnosci.d64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Wladcy ciemnosci.d64")}`,
  },
  {
    id: "zamczysko",
    name: "Zamczysko.t64",
    title: "Zamczysko",
    cleanTitle: "Zamczysko",
    ext: "t64",
    size: 49951,
    format: "T64",
    genre: "Tajemnicza Przygoda",
    year: 1992,
    publisher: "Mirage Interactive",
    author: "Marek G.",
    description: "Gra przygodowo-eksploracyjna na C64. Odkryj mroczne tajemnice prastarego zamczyska, rozwiązuj zagadki logiczne i znajdź drogę ucieczki z labiryntu korytarzy.",
    romUrl: "src/roms/games/polish_classics/Zamczysko.t64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Zamczysko.t64")}`,
  },
  {
    id: "zombi",
    name: "Zombi.T64",
    title: "Zombi (Polska Wersja C64)",
    cleanTitle: "Zombi",
    ext: "t64",
    size: 49951,
    format: "T64",
    genre: "Horror / Akcja",
    year: 1992,
    publisher: "Polskie Oprogramowanie C64",
    author: "Polska Grupa Retro",
    description: "Kultowy horror na taśmę kasetową C64. Przetrwaj inwazję żywych trupów, przeszukuj pomieszczenia w poszukiwaniu broni i paliwa do helikoptera ratunkowego.",
    romUrl: "src/roms/games/polish_classics/Zombi.T64",
    directDownloadUrl: `${GITHUB_POLISH_CLASSICS_REPO_BASE}${encodeURIComponent("Zombi.T64")}`,
  },
];

export const POLISH_CLASSICS = POLISH_CLASSICS_ROMS;

export function findPolishGameById(id: string): PolishGameRomEntry | undefined {
  return POLISH_CLASSICS_ROMS.find((g) => g.id === id || g.name.toLowerCase() === id.toLowerCase());
}
