[Partition Links]
DF0,A:\
DF1,B:\
DH0,C:\
DH1,D:\
A,A:\
B,B:\
C,C:\
D,D:\
E,E:\
F,F:\
G,G:\
H,H:\
I,I:\
J,J:\
K,K:\
L,L:\
M,M:\
N,N:\
O,O:\
P,P:\
Q,Q:\
R,R:\
S,S:\
T,T:\
U,U:\
V,V:\
W,W:\
X,X:\
Y,Y:\
Z,Z:\
[Security]
DefaultClass=Master
#Prompt Logon
#Allow Visitor Logons
[Preferences]
Percentage Display
Directory Load
Burst Loading
EMS
Virtual Mounts
[Ports]
&h378
&h278
&h3bc
&h2bc
[Printer]
DEV=PRN
[ARCHIVERS]
ZIP pkunzip @ %
LZH lha e @ %
LHA lha e @ %
ARJ arj e @ %
